"""Default application settings."""

DEFAULT_RECORDINGS_DIR = "recordings"
DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 720
DEFAULT_FPS = 30
DEFAULT_CAMERA_INDEX = 0
DEFAULT_WINDOW_NAME = "Virtual Drumming Pose Recorder"
DEFAULT_VIDEO_CODEC = "mp4v"
DEFAULT_VIDEO_QUEUE_SIZE = 256
DEFAULT_EXPORT_BUFFER_ROWS = 2048

